server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appdatabase
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  application:
    name: domain-header
#
#
#eureka:
#  client:
#    register-with-eureka: true
#    service-url:
#      default-zone: http://localhost:8761/eureka/
#
#jwt:
#  secret: "mou3a9kenTW44sSa3Feha"
