name: service registryconfig server CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup jdk
      uses: actions/setup-java@v3.5.0
      with:
        java-version: '18'
        distribution: 'temurin'
    
    - name: Build with Maven
      run:
        mvn clean install package

    - run: |
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
        docker build .  -t ${{ secrets.DOCKER_USER }}/domain-header:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USER }}/domain-header:${{ github.sha }}
   
    - name: announce the end
      run: echo "the eeee"


