name: service registryconfig server CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup jdk
      uses: actions/setup-java@v3.5.0
      with:
        java-version: '18'
        distribution: 'temurin'
    
    - name: Build with Maven
      run:
        mvn clean install package
        
    - uses: actions/upload-artifact@v3.1.0
      with:
        name: config-server-0.0.1
        path: target/
        
    - run: docker build . --file Dockerfile --tag ${{secrets.ACR_SERVER_URL}}/domain-header-asserter
    - name: login to ACR
      uses: Azure/docker-login@v1
      with:
        username: ${{secrets.ACR_USER}} 
        # Container registry password
        password: ${{secrets.ACR_PASSWORD}}
        # Container registry server url
        login-server: ${{secrets.ACR_SERVER_URL}}
    - name: push docker image to ACR
      run: |
        docker push ${{secrets.ACR_SERVER_URL}}/domain-header-asserter

