name: service registryconfig server CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup jdk
      uses: actions/setup-java@v3.5.0
      with:
        java-version: '18'
        distribution: 'temurin'
    
    - name: Build with Maven
      run:
        mvn clean install package
        
    - run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/domain-header-asserter
    - name: push docker image to dockerhub
      run: |
        docker login -u ${{DOCKER_USER}} -p ${{DOCKER_PASSWORD}}
        docker push ${{secrets.DOCKER_USER}}/domain-header-asserter

